{
 "title": "Cluster Exporter",
 "description": "Dashboard to view multiple servers",
 "tags": [ "cluster-monitor" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_boot_time, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu{instance=~\"$node\", mode=\"system\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"system\",instance=~'$node'}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='user',instance=~'$node'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='nice',instance=~'$node'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='iowait',instance=~'$node'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='steal',instance=~'$node'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~'$node'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='irq',instance=~'$node'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='softirq',instance=~'$node'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='guest',instance=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal{instance=~'$node'} - node_memory_MemFree{instance=~'$node'} - node_memory_Buffers{instance=~'$node'} - node_memory_Cached{instance=~'$node'} - node_memory_SwapCached{instance=~'$node'} - node_memory_Slab{instance=~'$node'} - node_memory_PageTables{instance=~'$node'} - node_memory_VmallocUsed{instance=~'$node'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers{instance=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{instance=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree{instance=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab{instance=~'$node'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached{instance=~'$node'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables{instance=~'$node'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed{instance=~'$node'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS{instance=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped{instance=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active{instance=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive{instance=~'$node'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "repeat": "node",
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches{instance=~\"$node\"}[5m])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{instance=~\"$node\"}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "repeat": "node",
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_sectors_read{instance=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_sectors_written{instance=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  }
 ]
}