/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_core_retina_Visibility */

#ifndef _Included_io_pixelsdb_pixels_core_retina_Visibility
#define _Included_io_pixelsdb_pixels_core_retina_Visibility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_core_retina_Visibility
 * Method:    destroyNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_core_retina_Visibility_destroyNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_core_retina_Visibility
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_core_retina_Visibility_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     io_pixelsdb_pixels_core_retina_Visibility
 * Method:    getReadableBitmap
 * Signature: (IJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_pixelsdb_pixels_core_retina_Visibility_getReadableBitmap
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_pixelsdb_pixels_core_retina_Visibility
 * Method:    deleteRow
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_core_retina_Visibility_deleteRow
  (JNIEnv *, jobject, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
