/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_retina_Visibility */

#ifndef _Included_io_pixelsdb_pixels_retina_Visibility
#define _Included_io_pixelsdb_pixels_retina_Visibility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_retina_Visibility
 * Method:    destroyNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Visibility_destroyNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Visibility
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_retina_Visibility_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     io_pixelsdb_pixels_retina_Visibility
 * Method:    getVisibilityBitmap
 * Signature: (J[JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Visibility_getVisibilityBitmap
  (JNIEnv *, jobject, jlong, jlongArray, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Visibility
 * Method:    deleteRecord
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Visibility_deleteRecord
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Visibility
 * Method:    createNewEpoch
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Visibility_createNewEpoch
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Visibility
 * Method:    cleanEpochArrAndPatchArr
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Visibility_cleanEpochArrAndPatchArr
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
