// automatically generated by the FlatBuffers compiler, do not modify

package io.pixelsdb.pixels.retina.util.flat;

@SuppressWarnings("unused")
public final class ColumnVectorBaseTypeFlat {
  private ColumnVectorBaseTypeFlat() { }
  public static final byte NONE = 0;
  public static final byte BINARY = 1;
  public static final byte BYTE = 2;
  public static final byte DATE = 3;
  public static final byte DECIMAL = 4;
  public static final byte DICTIONARY = 5;
  public static final byte DOUBLE = 6;
  public static final byte FLOAT = 7;
  public static final byte INT = 8;
  public static final byte LONG = 9;
  public static final byte LONGDECIMAL = 10;
  public static final byte STRUCT = 11;
  public static final byte TIME = 12;
  public static final byte TIMESTAMP = 13;
  public static final byte VECTOR = 14;

  public static final String[] names = { "NONE", "BINARY", "BYTE", "DATE", "DECIMAL", "DICTIONARY", "DOUBLE", "FLOAT", "INT", "LONG", "LONGDECIMAL", "STRUCT", "TIME", "TIMESTAMP", "VECTOR", };

  public static String name(int e) { return names[e]; }
}

