// automatically generated by the FlatBuffers compiler, do not modify

package io.pixelsdb.pixels.retina.util.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DecimalColumnVectorFlat extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static DecimalColumnVectorFlat getRootAsDecimalColumnVectorFlat(ByteBuffer _bb) { return getRootAsDecimalColumnVectorFlat(_bb, new DecimalColumnVectorFlat()); }
  public static DecimalColumnVectorFlat getRootAsDecimalColumnVectorFlat(ByteBuffer _bb, DecimalColumnVectorFlat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DecimalColumnVectorFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public io.pixelsdb.pixels.retina.util.flat.ColumnVectorBaseFlat base() { return base(new io.pixelsdb.pixels.retina.util.flat.ColumnVectorBaseFlat()); }
  public io.pixelsdb.pixels.retina.util.flat.ColumnVectorBaseFlat base(io.pixelsdb.pixels.retina.util.flat.ColumnVectorBaseFlat obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public long vector(int j) { int o = __offset(6); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int vectorLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public LongVector vectorVector() { return vectorVector(new LongVector()); }
  public LongVector vectorVector(LongVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer vectorAsByteBuffer() { return __vector_as_bytebuffer(6, 8); }
  public ByteBuffer vectorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 8); }
  public int precision() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int scale() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createDecimalColumnVectorFlat(FlatBufferBuilder builder,
      int baseOffset,
      int vectorOffset,
      int precision,
      int scale) {
    builder.startTable(4);
    DecimalColumnVectorFlat.addScale(builder, scale);
    DecimalColumnVectorFlat.addPrecision(builder, precision);
    DecimalColumnVectorFlat.addVector(builder, vectorOffset);
    DecimalColumnVectorFlat.addBase(builder, baseOffset);
    return DecimalColumnVectorFlat.endDecimalColumnVectorFlat(builder);
  }

  public static void startDecimalColumnVectorFlat(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addBase(FlatBufferBuilder builder, int baseOffset) { builder.addOffset(0, baseOffset, 0); }
  public static void addVector(FlatBufferBuilder builder, int vectorOffset) { builder.addOffset(1, vectorOffset, 0); }
  public static int createVectorVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startVectorVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addPrecision(FlatBufferBuilder builder, int precision) { builder.addInt(2, precision, 0); }
  public static void addScale(FlatBufferBuilder builder, int scale) { builder.addInt(3, scale, 0); }
  public static int endDecimalColumnVectorFlat(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DecimalColumnVectorFlat get(int j) { return get(new DecimalColumnVectorFlat(), j); }
    public DecimalColumnVectorFlat get(DecimalColumnVectorFlat obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

