// automatically generated by the FlatBuffers compiler, do not modify

package io.pixelsdb.pixels.retina.util.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FloatColumnVectorFlat extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static FloatColumnVectorFlat getRootAsFloatColumnVectorFlat(ByteBuffer _bb) { return getRootAsFloatColumnVectorFlat(_bb, new FloatColumnVectorFlat()); }
  public static FloatColumnVectorFlat getRootAsFloatColumnVectorFlat(ByteBuffer _bb, FloatColumnVectorFlat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FloatColumnVectorFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public io.pixelsdb.pixels.retina.util.flat.ColumnVectorBaseFlat base() { return base(new io.pixelsdb.pixels.retina.util.flat.ColumnVectorBaseFlat()); }
  public io.pixelsdb.pixels.retina.util.flat.ColumnVectorBaseFlat base(io.pixelsdb.pixels.retina.util.flat.ColumnVectorBaseFlat obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public int vector(int j) { int o = __offset(6); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int vectorLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public IntVector vectorVector() { return vectorVector(new IntVector()); }
  public IntVector vectorVector(IntVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer vectorAsByteBuffer() { return __vector_as_bytebuffer(6, 4); }
  public ByteBuffer vectorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 4); }

  public static int createFloatColumnVectorFlat(FlatBufferBuilder builder,
      int baseOffset,
      int vectorOffset) {
    builder.startTable(2);
    FloatColumnVectorFlat.addVector(builder, vectorOffset);
    FloatColumnVectorFlat.addBase(builder, baseOffset);
    return FloatColumnVectorFlat.endFloatColumnVectorFlat(builder);
  }

  public static void startFloatColumnVectorFlat(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addBase(FlatBufferBuilder builder, int baseOffset) { builder.addOffset(0, baseOffset, 0); }
  public static void addVector(FlatBufferBuilder builder, int vectorOffset) { builder.addOffset(1, vectorOffset, 0); }
  public static int createVectorVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startVectorVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFloatColumnVectorFlat(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FloatColumnVectorFlat get(int j) { return get(new FloatColumnVectorFlat(), j); }
    public FloatColumnVectorFlat get(FloatColumnVectorFlat obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

