/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_RocksetIndexStub */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_RocksetIndexStub
#define _Included_io_pixelsdb_pixels_index_rockset_RocksetIndexStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    CreateCloudFileSystem0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_CreateCloudFileSystem0
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    OpenDBCloud0
 * Signature: (JLjava/lang/String;Ljava/lang/String;JZ)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_OpenDBCloud0
  (JNIEnv *, jobject, jlong, jstring, jstring, jlong, jboolean);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    DBput0
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_DBput0
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    DBget0
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_DBget0
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    DBdelete0
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_DBdelete0
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    CloseDB0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_CloseDB0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    DBNewIterator0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_DBNewIterator0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    IteratorSeekForPrev0
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_IteratorSeekForPrev0
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    IteratorIsValid0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_IteratorIsValid0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    IteratorKey0
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_IteratorKey0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    IteratorValue0
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_IteratorValue0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    IteratorPrev0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_IteratorPrev0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    IteratorClose0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_IteratorClose0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    WriteBatchCreate0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_WriteBatchCreate0
  (JNIEnv *, jobject);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    WriteBatchPut0
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_WriteBatchPut0
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    WriteBatchDelete0
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_WriteBatchDelete0
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    DBWrite0
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_DBWrite0
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    WriteBatchClear0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_WriteBatchClear0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_RocksetIndexStub
 * Method:    WriteBatchDestroy0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_RocksetIndexStub_WriteBatchDestroy0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
