#!/usr/bin/env bash
set -euo pipefail

# Builds pixelsdb/pixels-trino once on the local machine and records the
# connector/listener zip paths for install_trino_cluster.sh to fan out to
# remote Trino nodes. This assumes Pixels itself has already been built with
# `mvn install` locally, as required by the pixels-trino project.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/shell_env.sh
source "$SCRIPT_DIR/lib/shell_env.sh"
load_toolchain_env

SKILL_DIR="${SKILL_DIR:-$(skill_dir)}"
STATE_DIR="${STATE_DIR:-$(state_dir)}"
REPO_ROOT="${REPO_ROOT:-$(require_repo_root)}"
PIXELS_TRINO_DIR="${PIXELS_TRINO_DIR:-$HOME/pixels-trino}"
PIXELS_TRINO_REPO_URL="${PIXELS_TRINO_REPO_URL:-https://github.com/pixelsdb/pixels-trino.git}"
PIXELS_TRINO_ARTIFACT_DIR="${PIXELS_TRINO_ARTIFACT_DIR:-$STATE_DIR/pixels-trino-artifacts}"
PIXELS_TRINO_ARTIFACTS_ENV="${PIXELS_TRINO_ARTIFACTS_ENV:-$STATE_DIR/pixels-trino-artifacts.env}"
ASSUME_YES="${ASSUME_YES:-false}"
CONFIRM_PIXELS_TRINO_ARTIFACTS="${CONFIRM_PIXELS_TRINO_ARTIFACTS:-}"

log() {
  printf '[%s] %s\n' "$(date '+%H:%M:%S')" "$*"
}

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 command not found"
}

require_java() {
  local derived_home

  if [[ -z "${JAVA_HOME:-}" || ! -x "${JAVA_HOME:-}/bin/java" ]]; then
    derived_home="$(locate_existing_java_home || true)"
    [[ -n "$derived_home" ]] && export JAVA_HOME="$derived_home"
  fi

  [[ -n "${JAVA_HOME:-}" && -x "$JAVA_HOME/bin/java" ]] ||
    fail "JAVA_HOME is not set to a valid JDK; run install_jdk.sh first"
}

confirm_build() {
  local reply

  case "$CONFIRM_PIXELS_TRINO_ARTIFACTS" in
    true) return ;;
    false) fail "CONFIRM_PIXELS_TRINO_ARTIFACTS=false" ;;
  esac
  [[ "$ASSUME_YES" == "true" ]] && return

  printf '\npixels-trino artifact build summary:\n'
  printf '  pixels repo: %s\n' "$REPO_ROOT"
  printf '  pixels-trino repo: %s\n' "$PIXELS_TRINO_DIR"
  printf '  artifact dir: %s\n' "$PIXELS_TRINO_ARTIFACT_DIR"
  printf '  output env: %s\n\n' "$PIXELS_TRINO_ARTIFACTS_ENV"

  [[ -t 0 ]] || fail "pixels-trino artifact build must be confirmed; set CONFIRM_PIXELS_TRINO_ARTIFACTS=true after reviewing paths"
  read -r -p "Build pixels-trino connector/listener artifacts locally? [y/N]: " reply
  [[ "$reply" =~ ^[Yy]$ ]] || fail "aborted pixels-trino artifact build"
}

clone_or_update_pixels_trino() {
  if [[ -d "$PIXELS_TRINO_DIR/.git" ]]; then
    log "using existing pixels-trino checkout: $PIXELS_TRINO_DIR"
    return
  fi

  require_command git
  log "cloning pixels-trino into $PIXELS_TRINO_DIR"
  git clone "$PIXELS_TRINO_REPO_URL" "$PIXELS_TRINO_DIR"
}

build_artifacts() {
  require_java
  require_command mvn

  log "building pixels-trino (requires Pixels modules already installed into the local Maven repository)"
  (cd "$PIXELS_TRINO_DIR" && mvn clean install) || fail "pixels-trino build failed"
}

record_artifacts() {
  local connector_zip listener_zip connector_target listener_target

  connector_zip="$(find "$PIXELS_TRINO_DIR/connector/target" -maxdepth 1 -name 'pixels-trino-connector-*.zip' -print -quit 2>/dev/null || true)"
  listener_zip="$(find "$PIXELS_TRINO_DIR/listener/target" -maxdepth 1 -name 'pixels-trino-listener-*.zip' -print -quit 2>/dev/null || true)"
  [[ -n "$connector_zip" && -f "$connector_zip" ]] || fail "pixels-trino connector zip not found under $PIXELS_TRINO_DIR/connector/target"
  [[ -n "$listener_zip" && -f "$listener_zip" ]] || fail "pixels-trino listener zip not found under $PIXELS_TRINO_DIR/listener/target"

  mkdir -p "$PIXELS_TRINO_ARTIFACT_DIR" "$(dirname "$PIXELS_TRINO_ARTIFACTS_ENV")"
  connector_target="$PIXELS_TRINO_ARTIFACT_DIR/$(basename "$connector_zip")"
  listener_target="$PIXELS_TRINO_ARTIFACT_DIR/$(basename "$listener_zip")"
  cp "$connector_zip" "$connector_target"
  cp "$listener_zip" "$listener_target"

  cat > "$PIXELS_TRINO_ARTIFACTS_ENV" <<EOF
# Generated by pixels-install/scripts/build_pixels_trino_artifacts.sh
PIXELS_TRINO_CONNECTOR_ZIP=$(printf '%q' "$connector_target")
PIXELS_TRINO_LISTENER_ZIP=$(printf '%q' "$listener_target")
INSTALL_PIXELS_TRINO_LISTENER=true
EOF

  log "recorded pixels-trino artifacts:"
  log "  connector: $connector_target"
  log "  listener:  $listener_target"
  log "  env:       $PIXELS_TRINO_ARTIFACTS_ENV"
}

main() {
  confirm_build
  clone_or_update_pixels_trino
  build_artifacts
  record_artifacts
}

main "$@"
