#!/usr/bin/env bash
set -euo pipefail

# Installs Pixels shell functions for day-to-day operation. This is a
# user-scoped convenience (only the current user's shell profile is edited),
# but it still asks first because it changes the user's interactive shell and
# may bake the current skill/state paths into a redeploy helper.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/shell_env.sh
source "$SCRIPT_DIR/lib/shell_env.sh"
load_toolchain_env

SKILL_DIR="${SKILL_DIR:-$(skill_dir)}"
PIXELS_HOME="${PIXELS_HOME:-$HOME/opt/pixels}"
PIXELS_FUNCTIONS_FILE="${PIXELS_FUNCTIONS_FILE:-$HOME/.pixels-shell-helpers.sh}"
PIXELS_INSTALL_SKILL_DIR="${PIXELS_INSTALL_SKILL_DIR:-$SKILL_DIR}"
ASSUME_YES="${ASSUME_YES:-false}"
INSTALL_PIXELS_SHELL_HELPERS="${INSTALL_PIXELS_SHELL_HELPERS:-}"

log() {
  printf '[%s] %s\n' "$(date '+%H:%M:%S')" "$*"
}

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

confirm_install() {
  local reply

  case "$INSTALL_PIXELS_SHELL_HELPERS" in
    true) return 0 ;;
    false) return 1 ;;
  esac

  [[ "$ASSUME_YES" == "true" ]] && return 0

  if [[ ! -t 0 ]]; then
    log "not running interactively and INSTALL_PIXELS_SHELL_HELPERS/ASSUME_YES not set; skipping the Pixels shell helpers. Set INSTALL_PIXELS_SHELL_HELPERS=true once the user has agreed."
    return 1
  fi

  read -r -p "Install start/stop/restart/redeploy Pixels shell functions (writes $PIXELS_FUNCTIONS_FILE)? [y/N]: " reply
  [[ "$reply" =~ ^[Yy]$ ]]
}

write_functions_file() {
  log "writing start_pixels/stop_pixels/restart_pixels to $PIXELS_FUNCTIONS_FILE"

  cat > "$PIXELS_FUNCTIONS_FILE" <<EOF
# Generated by pixels-install/scripts/install_shell_helpers.sh
# Provides Pixels local helpers plus optional stack helpers that call Trino
# helpers when start_trino_cluster/stop_trino_cluster/restart_trino_cluster
# are installed in the current shell.

_pixels_home() {
  printf '%s\n' "\${PIXELS_HOME:-$PIXELS_HOME}"
}

_pixels_install_skill_dir() {
  printf '%s\n' "\${PIXELS_INSTALL_SKILL_DIR:-$PIXELS_INSTALL_SKILL_DIR}"
}

_pixels_has_function() {
  declare -F "\$1" >/dev/null 2>&1
}

_pixels_call_trino_helper() {
  local fn="\$1"
  if _pixels_has_function "\$fn"; then
    "\$fn"
  else
    echo "\$fn is not defined; skipping Trino cluster operation"
  fi
}

start_pixels() {
  local pixels_home

  pixels_home="\$(_pixels_home)"
  "\$pixels_home/sbin/start-pixels.sh" || { echo "failed to start pixels" >&2; return 1; }
  echo "pixels started"
}

stop_pixels() {
  local pixels_home

  pixels_home="\$(_pixels_home)"
  "\$pixels_home/sbin/stop-pixels.sh" || { echo "failed to stop pixels" >&2; return 1; }
  echo "pixels stopped"
}

restart_pixels() {
  stop_pixels || return 1
  start_pixels || return 1
  echo "pixels restarted"
}

redeploy_pixels() {
  local skill_dir

  skill_dir="\$(_pixels_install_skill_dir)"
  if [[ ! -x "\$skill_dir/scripts/build_install_pixels.sh" || ! -x "\$skill_dir/scripts/configure_pixels.sh" ]]; then
    echo "pixels-install scripts not found under \$skill_dir" >&2
    return 1
  fi

  "\$skill_dir/scripts/build_install_pixels.sh" || return 1
  "\$skill_dir/scripts/configure_pixels.sh" || return 1
}

start_pixels_stack() {
  start_pixels || return 1
  _pixels_call_trino_helper start_trino_cluster || return 1
}

stop_pixels_stack() {
  _pixels_call_trino_helper stop_trino_cluster || return 1
  stop_pixels || return 1
}

restart_pixels_stack() {
  stop_pixels_stack || return 1
  start_pixels_stack || return 1
}

redeploy_pixels_stack() {
  _pixels_call_trino_helper stop_trino_cluster || return 1
  redeploy_pixels || return 1
  _pixels_call_trino_helper start_trino_cluster || return 1
}
EOF

  chmod 644 "$PIXELS_FUNCTIONS_FILE"
}

persist_source_line() {
  local profile_file line

  profile_file="$(detect_profile_file)"
  line="[ -f \"$PIXELS_FUNCTIONS_FILE\" ] && source \"$PIXELS_FUNCTIONS_FILE\""

  log "persisting source line for $PIXELS_FUNCTIONS_FILE in $profile_file"
  persist_line "$profile_file" "$line"
}

verify_functions_file() {
  bash -n "$PIXELS_FUNCTIONS_FILE" || fail "generated functions file has a syntax error: $PIXELS_FUNCTIONS_FILE"

  if [[ ! -x "$PIXELS_HOME/sbin/start-pixels.sh" ]]; then
    log "note: $PIXELS_HOME/sbin/start-pixels.sh not found yet; the functions are installed but will fail until Pixels itself is installed there"
  fi
}

main() {
  if ! confirm_install; then
    log "skipping Pixels shell helpers (not confirmed)"
    return 0
  fi

  write_functions_file
  verify_functions_file
  persist_source_line

  log "shell helpers installed: start_pixels, stop_pixels, restart_pixels, redeploy_pixels, start_pixels_stack, stop_pixels_stack, restart_pixels_stack, redeploy_pixels_stack"
  log "open a new terminal (or run: source $(detect_profile_file)) to use them"
}

main "$@"
