#!/usr/bin/env bash
set -euo pipefail

# Installs start_pixels/stop_pixels/restart_pixels shell functions for quick
# day-to-day operation, similar in spirit to install_etcd.sh's systemd unit
# but purely a user-scoped convenience: it only edits the current user's
# shell profile (never system-wide state), so unlike the etcd systemd unit
# this does not need an explicit confirmation prompt.
#
# Trino is out of pixels-install's scope (see docs/INSTALL.md and this
# skill's "Optional Components"), so these functions never install or
# require Trino: they only touch it if the user's shell already has
# TRINO_HOME pointing at a real Trino install, and skip that step
# (without failing) otherwise.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/shell_env.sh
source "$SCRIPT_DIR/lib/shell_env.sh"
load_toolchain_env

PIXELS_HOME="${PIXELS_HOME:-$HOME/opt/pixels}"
PIXELS_FUNCTIONS_FILE="${PIXELS_FUNCTIONS_FILE:-$HOME/.pixels-shell-helpers.sh}"

log() {
  printf '[%s] %s\n' "$(date '+%H:%M:%S')" "$*"
}

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

write_functions_file() {
  log "writing start_pixels/stop_pixels/restart_pixels to $PIXELS_FUNCTIONS_FILE"

  cat > "$PIXELS_FUNCTIONS_FILE" <<EOF
# Generated by pixels-install/scripts/install_shell_helpers.sh
# Provides start_pixels/stop_pixels/restart_pixels shell functions.
# Trino is optional and out of pixels-install's scope: these functions only
# touch Trino if your shell already has TRINO_HOME set and
# \$TRINO_HOME/bin/launcher exists; otherwise they skip it without failing.
# Safe to re-run pixels-install's install_shell_helpers.sh to regenerate
# this file (e.g. after PIXELS_HOME changes).

_pixels_home() {
  printf '%s\n' "\${PIXELS_HOME:-$PIXELS_HOME}"
}

_pixels_trino_launcher() {
  [[ -n "\${TRINO_HOME:-}" && -x "\$TRINO_HOME/bin/launcher" ]] || return 1
  printf '%s\n' "\$TRINO_HOME/bin/launcher"
}

start_pixels() {
  local pixels_home launcher

  pixels_home="\$(_pixels_home)"
  "\$pixels_home/sbin/start-pixels.sh" || { echo "failed to start pixels" >&2; return 1; }

  if launcher="\$(_pixels_trino_launcher)"; then
    "\$launcher" start || { echo "failed to start trino" >&2; return 1; }
  else
    echo "TRINO_HOME not set (or launcher missing); skipping trino startup"
  fi

  echo "pixels started"
}

stop_pixels() {
  local pixels_home launcher

  pixels_home="\$(_pixels_home)"
  "\$pixels_home/sbin/stop-pixels.sh" || { echo "failed to stop pixels" >&2; return 1; }

  if launcher="\$(_pixels_trino_launcher)"; then
    "\$launcher" stop || { echo "failed to stop trino" >&2; return 1; }
  else
    echo "TRINO_HOME not set (or launcher missing); skipping trino shutdown"
  fi

  echo "pixels stopped"
}

restart_pixels() {
  local pixels_home launcher

  pixels_home="\$(_pixels_home)"
  "\$pixels_home/sbin/stop-pixels.sh" || { echo "failed to stop pixels" >&2; return 1; }
  "\$pixels_home/sbin/start-pixels.sh" || { echo "failed to start pixels" >&2; return 1; }

  if launcher="\$(_pixels_trino_launcher)"; then
    "\$launcher" restart || { echo "failed to restart trino" >&2; return 1; }
  else
    echo "TRINO_HOME not set (or launcher missing); skipping trino restart"
  fi

  echo "pixels restarted"
}
EOF

  chmod 644 "$PIXELS_FUNCTIONS_FILE"
}

persist_source_line() {
  local profile_file line

  profile_file="$(detect_profile_file)"
  line="[ -f \"$PIXELS_FUNCTIONS_FILE\" ] && source \"$PIXELS_FUNCTIONS_FILE\""

  log "persisting source line for $PIXELS_FUNCTIONS_FILE in $profile_file"
  persist_line "$profile_file" "$line"
}

verify_functions_file() {
  bash -n "$PIXELS_FUNCTIONS_FILE" || fail "generated functions file has a syntax error: $PIXELS_FUNCTIONS_FILE"

  if [[ ! -x "$PIXELS_HOME/sbin/start-pixels.sh" ]]; then
    log "note: $PIXELS_HOME/sbin/start-pixels.sh not found yet; the functions are installed but will fail until Pixels itself is installed there"
  fi
}

main() {
  write_functions_file
  verify_functions_file
  persist_source_line

  log "shell helpers installed: start_pixels, stop_pixels, restart_pixels"
  log "open a new terminal (or run: source $(detect_profile_file)) to use them"
}

main "$@"
