/*
 * Copyright 2022 PixelsDB.
 *
 * This file is part of Pixels.
 *
 * Pixels is free software: you can redistribute it and/or modify
 * it under the terms of the Affero GNU General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * Pixels is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Affero GNU General Public License for more details.
 *
 * You should have received a copy of the Affero GNU General Public
 * License along with Pixels.  If not, see
 * <https://www.gnu.org/licenses/>.
 */
package io.pixelsdb.pixels.common.turbo;

import java.util.ArrayList;

import static java.util.Objects.requireNonNull;

/**
 * The base class for the output of a cloud function (serverless) worker.
 * @author hank
 * @create 2022-06-28
 */
public abstract class Output
{
    /**
     * The request id of the serverless worker.
     * It is generated by the cloud function service and is unique for each serverless worker.
     */
    private String requestId;
    /**
     * True if the execution of the serverless worker is successful.
     */
    private boolean successful;
    /**
     * Error message of the serverless worker if execution failed. It is null or empty on success execution.
     */
    private String errorMessage;
    /**
     * The start time of the serverless worker.
     */
    private long startTimeMs;
    /**
     * The execution duration of the serverless worker.
     */
    private int durationMs;
    /**
     * The size of memory allocated to the serverless worker.
     */
    private int memoryMB;
    /**
     * The cumulative CPU time for reading input.
     */
    private int cumulativeInputCostMs;
    /**
     * The cumulative CPU time for pure computing.
     */
    private int cumulativeComputeCostMs;
    /**
     * The cumulative CPU time for writing output.
     */
    private int cumulativeOutputCostMs;
    /**
     * The number of read requests the serverless worker sends to the underlying storage.
     */
    private int numReadRequests;
    /**
     * The number of write requests the serverless worker sends to the underlying storage.
     */
    private int numWriteRequests;
    /**
     * The bytes the serverless worker reads from the underlying storage.
     */
    private long totalReadBytes;
    /**
     * The bytes the serverless worker writes to the underlying storage.
     */
    private long totalWriteBytes;
    /**
     * The path of the result files. No need to contain endpoint information.
     */
    private ArrayList<String> outputs = new ArrayList<>();

    public String getRequestId()
    {
        return requestId;
    }

    public void setRequestId(String requestId)
    {
        this.requestId = requestId;
    }

    public boolean isSuccessful()
    {
        return successful;
    }

    public void setSuccessful(boolean successful)
    {
        this.successful = successful;
    }

    public String getErrorMessage()
    {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage)
    {
        this.errorMessage = errorMessage;
    }

    public long getStartTimeMs()
    {
        return startTimeMs;
    }

    public void setStartTimeMs(long startTimeMs)
    {
        this.startTimeMs = startTimeMs;
    }

    public int getDurationMs()
    {
        return durationMs;
    }

    public void setDurationMs(int durationMs)
    {
        this.durationMs = durationMs;
    }

    public int getMemoryMB()
    {
        return memoryMB;
    }

    public void setMemoryMB(int memoryMB)
    {
        this.memoryMB = memoryMB;
    }

    /**
     * @return the GB-ms billed for this function request
     */
    public long getGBMs()
    {
        return Math.round(this.durationMs * (this.memoryMB / 1024.0d));
    }

    public int getCumulativeInputCostMs()
    {
        return cumulativeInputCostMs;
    }

    public void setCumulativeInputCostMs(int cumulativeInputCostMs)
    {
        this.cumulativeInputCostMs = cumulativeInputCostMs;
    }

    public int getCumulativeComputeCostMs()
    {
        return cumulativeComputeCostMs;
    }

    public void setCumulativeComputeCostMs(int cumulativeComputeCostMs)
    {
        this.cumulativeComputeCostMs = cumulativeComputeCostMs;
    }

    public int getCumulativeOutputCostMs()
    {
        return cumulativeOutputCostMs;
    }

    public void setCumulativeOutputCostMs(int cumulativeOutputCostMs)
    {
        this.cumulativeOutputCostMs = cumulativeOutputCostMs;
    }

    public int getNumReadRequests()
    {
        return numReadRequests;
    }

    public void setNumReadRequests(int numReadRequests)
    {
        this.numReadRequests = numReadRequests;
    }

    public int getNumWriteRequests()
    {
        return numWriteRequests;
    }

    public void setNumWriteRequests(int numWriteRequests)
    {
        this.numWriteRequests = numWriteRequests;
    }

    public long getTotalReadBytes()
    {
        return totalReadBytes;
    }

    public void setTotalReadBytes(long totalReadBytes)
    {
        this.totalReadBytes = totalReadBytes;
    }

    public long getTotalWriteBytes()
    {
        return totalWriteBytes;
    }

    public void setTotalWriteBytes(long totalWriteBytes)
    {
        this.totalWriteBytes = totalWriteBytes;
    }

    public ArrayList<String> getOutputs()
    {
        return outputs;
    }

    public void setOutputs(ArrayList<String> outputs)
    {
        this.outputs = requireNonNull(outputs, "outputs is null");
    }

    public synchronized void addOutput(String output)
    {
        this.outputs.add(output);
    }

    public SimpleOutput toSimpleOutput()
    {
        SimpleOutput simpleOutput = new SimpleOutput();
        simpleOutput.setRequestId(this.requestId);
        simpleOutput.setSuccessful(this.successful);
        simpleOutput.setErrorMessage(this.errorMessage != null ? this.errorMessage : "");
        simpleOutput.setNumOutputs(this.outputs.size());
        return simpleOutput;
    }
}
