# pixels server configuration
server_address: ec2-18-218-128-203.us-east-2.compute.amazonaws.com
server_port: 18892
metadata_service_port: 18888

# trino configuration
trino_url: ec2-18-218-128-203.us-east-2.compute.amazonaws.com
trino_port: 8080
trino_default_catalog: pixels
trino_default_schema: tpch_1g

# cache configuration
cache_dir_path: ./data

# database configuration
local_engine: duckdb
remote_engine: hive