/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_ruc_iir_pixels_cache_NativePixelsCacheReader */

#ifndef _Included_cn_edu_ruc_iir_pixels_cache_NativePixelsCacheReader
#define _Included_cn_edu_ruc_iir_pixels_cache_NativePixelsCacheReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_ruc_iir_pixels_cache_NativePixelsCacheReader
 * Method:    get
 * Signature: (JSS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_edu_ruc_iir_pixels_cache_NativePixelsCacheReader_get
  (JNIEnv *, jclass, jlong, jshort, jshort);

/*
 * Class:     cn_edu_ruc_iir_pixels_cache_NativePixelsCacheReader
 * Method:    sch
 * Signature: (JSS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_edu_ruc_iir_pixels_cache_NativePixelsCacheReader_sch
  (JNIEnv *, jclass, jlong, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
