/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_NativePixelsCacheReader */

#ifndef _Included_io_pixelsdb_pixels_cache_NativePixelsCacheReader
#define _Included_io_pixelsdb_pixels_cache_NativePixelsCacheReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_cache_NativePixelsCacheReader
 * Method:    get
 * Signature: (JSS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pixelsdb_pixels_cache_NativePixelsCacheReader_get
  (JNIEnv *, jclass, jlong, jshort, jshort);

/*
 * Class:     io_pixelsdb_pixels_cache_NativePixelsCacheReader
 * Method:    sch
 * Signature: (JSS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pixelsdb_pixels_cache_NativePixelsCacheReader_sch
  (JNIEnv *, jclass, jlong, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
