/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetStatistics */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetStatistics
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetStatistics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetStatistics
 * Method:    newStatisticsInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetStatistics_newStatisticsInstance
  (JNIEnv *, jclass);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetStatistics
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetStatistics_disposeInternalJni
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
