/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetLRUCache */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetLRUCache
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetLRUCache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetLRUCache
 * Method:    newLRUCache
 * Signature: (JIZDD)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetLRUCache_newLRUCache
  (JNIEnv *, jclass, jlong, jint, jboolean, jdouble, jdouble);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetLRUCache
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetLRUCache_disposeInternalJni
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
