/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyHandle */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyHandle
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyHandle
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyHandle_disposeInternalJni
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
