/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetWriteOptions */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteOptions
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetWriteOptions
 * Method:    newWriteOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteOptions_newWriteOptions
  (JNIEnv *, jclass);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetWriteOptions
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteOptions_disposeInternalJni
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
