/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch
 * Method:    newWriteBatch0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch_newWriteBatch0
  (JNIEnv *, jclass);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch_disposeInternalJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch
 * Method:    putDirectJni
 * Signature: (JLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch_putDirectJni
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jobject, jint, jint, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch
 * Method:    deleteJni
 * Signature: (J[BIJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetWriteBatch_deleteJni
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
