/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetBloomFilter */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetBloomFilter
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetBloomFilter
#ifdef __cplusplus
extern "C" {
#endif
#undef io_pixelsdb_pixels_index_rockset_jni_RocksetBloomFilter_DEFAULT_BITS_PER_KEY
#define io_pixelsdb_pixels_index_rockset_jni_RocksetBloomFilter_DEFAULT_BITS_PER_KEY 10.0
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetBloomFilter
 * Method:    createNewBloomFilter
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetBloomFilter_createNewBloomFilter
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
