/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_MemoryUtil */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_MemoryUtil
#define _Included_io_pixelsdb_pixels_index_rockset_jni_MemoryUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_MemoryUtil
 * Method:    getApproximateMemoryUsageByType
 * Signature: ([J[J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_MemoryUtil_getApproximateMemoryUsageByType
  (JNIEnv *, jclass, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
