/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetIterator */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetIterator
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetIterator
 * Method:    seekDirect0Jni
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetIterator_seekDirect0Jni
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetIterator
 * Method:    seekByteArray0Jni
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetIterator_seekByteArray0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetIterator
 * Method:    next0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetIterator_next0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetIterator
 * Method:    isValid0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetIterator_isValid0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetIterator
 * Method:    key0
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetIterator_key0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetIterator
 * Method:    value0
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetIterator_value0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetIterator
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetIterator_disposeInternalJni
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
