/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetBlockBasedTableConfig */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetBlockBasedTableConfig
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetBlockBasedTableConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetBlockBasedTableConfig
 * Method:    newTableFactoryHandle
 * Signature: (JJJZ)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetBlockBasedTableConfig_newTableFactoryHandle
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
