/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    newColumnFamilyOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_newColumnFamilyOptions
  (JNIEnv *, jclass);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetWriteBufferSize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetWriteBufferSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetMaxWriteBufferNumber
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetMaxWriteBufferNumber
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetMinWriteBufferNumberToMerge
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetMinWriteBufferNumberToMerge
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetMemtablePrefixBloomSizeRatio
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetMemtablePrefixBloomSizeRatio
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetTableFactory
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetTableFactory
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetLevel0FileNumCompactionTrigger
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetLevel0FileNumCompactionTrigger
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetMaxBytesForLevelBase
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetMaxBytesForLevelBase
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetMaxBytesForLevelMultiplier
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetMaxBytesForLevelMultiplier
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetTargetFileSizeBase
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetTargetFileSizeBase
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetTargetFileSizeMultiplier
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetTargetFileSizeMultiplier
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetCompressionType
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetCompressionType
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetBottommostCompressionType
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetBottommostCompressionType
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    nativeSetCompactionStyle
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_nativeSetCompactionStyle
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetColumnFamilyOptions_disposeInternalJni
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
