/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    newDBOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_newDBOptions
  (JNIEnv *, jclass);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_disposeInternalJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    nativeSetCreateIfMissing
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_nativeSetCreateIfMissing
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    nativeSetCreateMissingColumnFamilies
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_nativeSetCreateMissingColumnFamilies
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    nativeSetMaxBackgroundFlushes
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_nativeSetMaxBackgroundFlushes
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    nativeSetMaxBackgroundCompactions
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_nativeSetMaxBackgroundCompactions
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    nativeSetMaxSubcompactions
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_nativeSetMaxSubcompactions
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    nativeSetMaxOpenFiles
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_nativeSetMaxOpenFiles
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    nativeSetStatistics
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_nativeSetStatistics
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    nativeSetStatsDumpPeriodSec
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_nativeSetStatsDumpPeriodSec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions
 * Method:    nativeSetDbLogDir
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDBOptions_nativeSetDbLogDir
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
