/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetDB */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetDB
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDB
 * Method:    closeDatabase
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDB_closeDatabase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDB
 * Method:    open
 * Signature: (JJLjava/lang/String;[[B[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDB_open
  (JNIEnv *, jclass, jlong, jlong, jstring, jobjectArray, jlongArray);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDB
 * Method:    listColumnFamilies0
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDB_listColumnFamilies0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDB
 * Method:    createColumnFamily
 * Signature: ([B)Lio/pixelsdb/pixels/index/rockset/jni/RocksetColumnFamilyHandle;
 */
JNIEXPORT jobject JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDB_createColumnFamily
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDB
 * Method:    putDirect
 * Signature: (JJLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDB_putDirect
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint, jobject, jint, jint, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDB
 * Method:    put
 * Signature: (JJ[BII[BIIJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDB_put
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDB
 * Method:    write0
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDB_write0
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetDB
 * Method:    iterator
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetDB_iterator
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
