/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_index_rockset_jni_RocksetEnv */

#ifndef _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetEnv
#define _Included_io_pixelsdb_pixels_index_rockset_jni_RocksetEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetEnv
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetEnv_disposeInternalJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pixelsdb_pixels_index_rockset_jni_RocksetEnv
 * Method:    createCloudFileSystem0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_index_rockset_jni_RocksetEnv_createCloudFileSystem0
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
