# Path relevant to scripts/
schema_path: ../schema/tpch.json
table_stat_path: ../schema/tpch_stat_1g.json
workload_path: ../workload/tpch.txt

# Strategy options
strategy: most_coverage_columns
storage_restriction: 154119190