/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_utils_RadixIndexEndianRewriter */

#ifndef _Included_io_pixelsdb_pixels_cache_utils_RadixIndexEndianRewriter
#define _Included_io_pixelsdb_pixels_cache_utils_RadixIndexEndianRewriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_cache_utils_RadixIndexEndianRewriter
 * Method:    rewrite
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_cache_utils_RadixIndexEndianRewriter_rewrite
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
