/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_NativeHashIndexReader */

#ifndef _Included_io_pixelsdb_pixels_cache_NativeHashIndexReader
#define _Included_io_pixelsdb_pixels_cache_NativeHashIndexReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_cache_NativeHashIndexReader
 * Method:    doNativeSearch
 * Signature: (JJJSSJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_cache_NativeHashIndexReader_doNativeSearch
  (JNIEnv *, jobject, jlong, jlong, jlong, jshort, jshort, jlong);

#ifdef __cplusplus
}
#endif
#endif
