/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_utils_RadixTreeDumper */

#ifndef _Included_io_pixelsdb_pixels_cache_utils_RadixTreeDumper
#define _Included_io_pixelsdb_pixels_cache_utils_RadixTreeDumper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_cache_utils_RadixTreeDumper
 * Method:    nativeTraverse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_cache_utils_RadixTreeDumper_nativeTraverse
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
