/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_PixelsNativeCacheReader_Builder */

#ifndef _Included_io_pixelsdb_pixels_cache_PixelsNativeCacheReader_Builder
#define _Included_io_pixelsdb_pixels_cache_PixelsNativeCacheReader_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
