/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_PixelsNativeCacheReader */

#ifndef _Included_io_pixelsdb_pixels_cache_PixelsNativeCacheReader
#define _Included_io_pixelsdb_pixels_cache_PixelsNativeCacheReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_cache_PixelsNativeCacheReader
 * Method:    search
 * Signature: (JJLjava/nio/ByteBuffer;JSS)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_cache_PixelsNativeCacheReader_search
  (JNIEnv *, jobject, jlong, jlong, jobject, jlong, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
