/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_NativeDiskCacheContentReader */

#ifndef _Included_io_pixelsdb_pixels_cache_NativeDiskCacheContentReader
#define _Included_io_pixelsdb_pixels_cache_NativeDiskCacheContentReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_cache_NativeDiskCacheContentReader
 * Method:    read
 * Signature: (JILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_cache_NativeDiskCacheContentReader_read
  (JNIEnv *, jobject, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
