/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_CacheIndexSerializer */

#ifndef _Included_io_pixelsdb_pixels_cache_CacheIndexSerializer
#define _Included_io_pixelsdb_pixels_cache_CacheIndexSerializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_cache_CacheIndexSerializer
 * Method:    traverse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_cache_CacheIndexSerializer_traverse
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
