/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_CacheIndexRewriter */

#ifndef _Included_io_pixelsdb_pixels_cache_CacheIndexRewriter
#define _Included_io_pixelsdb_pixels_cache_CacheIndexRewriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_cache_CacheIndexRewriter
 * Method:    rewrite
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_cache_CacheIndexRewriter_rewrite
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
