/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_retina_Retina */

#ifndef _Included_io_pixelsdb_pixels_retina_Retina
#define _Included_io_pixelsdb_pixels_retina_Retina
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_retina_Retina
 * Method:    createNativeObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_retina_Retina_createNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Retina
 * Method:    destroyNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Retina_destroyNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Retina
 * Method:    beginAccess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Retina_beginAccess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Retina
 * Method:    endAccess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Retina_endAccess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Retina
 * Method:    deleteRecord
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Retina_deleteRecord
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Retina
 * Method:    getVisibilityBitmap
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_pixelsdb_pixels_retina_Retina_getVisibilityBitmap
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Retina
 * Method:    beginGarbageCollect
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Retina_beginGarbageCollect
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_Retina
 * Method:    endGarbageCollect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_Retina_endGarbageCollect
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
