/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_retina_RGVisibility */

#ifndef _Included_io_pixelsdb_pixels_retina_RGVisibility
#define _Included_io_pixelsdb_pixels_retina_RGVisibility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_retina_RGVisibility
 * Method:    createNativeObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_pixelsdb_pixels_retina_RGVisibility_createNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_RGVisibility
 * Method:    destroyNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_RGVisibility_destroyNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_RGVisibility
 * Method:    deleteRecord
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_RGVisibility_deleteRecord
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_RGVisibility
 * Method:    getVisibilityBitmap
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_pixelsdb_pixels_retina_RGVisibility_getVisibilityBitmap
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_pixelsdb_pixels_retina_RGVisibility
 * Method:    garbageCollect
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_retina_RGVisibility_garbageCollect
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
