// automatically generated by the FlatBuffers compiler, do not modify

package io.pixelsdb.pixels.core.utils.flat;

@SuppressWarnings("unused")
public final class ColumnVectorFlat {
  private ColumnVectorFlat() { }
  public static final byte NONE = 0;
  public static final byte BinaryColumnVectorFlat = 1;
  public static final byte ByteColumnVectorFlat = 2;
  public static final byte DateColumnVectorFlat = 3;
  public static final byte DecimalColumnVectorFlat = 4;
  public static final byte DictionaryColumnVectorFlat = 5;
  public static final byte DoubleColumnVectorFlat = 6;
  public static final byte FloatColumnVectorFlat = 7;
  public static final byte IntColumnVectorFlat = 8;
  public static final byte LongColumnVectorFlat = 9;
  public static final byte LongDecimalColumnVectorFlat = 10;
  public static final byte TimeColumnVectorFlat = 11;
  public static final byte TimestampColumnVectorFlat = 12;
  public static final byte VectorColumnVectorFlat = 13;

  public static final String[] names = { "NONE", "BinaryColumnVectorFlat", "ByteColumnVectorFlat", "DateColumnVectorFlat", "DecimalColumnVectorFlat", "DictionaryColumnVectorFlat", "DoubleColumnVectorFlat", "FloatColumnVectorFlat", "IntColumnVectorFlat", "LongColumnVectorFlat", "LongDecimalColumnVectorFlat", "TimeColumnVectorFlat", "TimestampColumnVectorFlat", "VectorColumnVectorFlat", };

  public static String name(int e) { return names[e]; }
}

