// automatically generated by the FlatBuffers compiler, do not modify

package io.pixelsdb.pixels.core.utils.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StructColumnVectorFlat extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static StructColumnVectorFlat getRootAsStructColumnVectorFlat(ByteBuffer _bb) { return getRootAsStructColumnVectorFlat(_bb, new StructColumnVectorFlat()); }
  public static StructColumnVectorFlat getRootAsStructColumnVectorFlat(ByteBuffer _bb, StructColumnVectorFlat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StructColumnVectorFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat base() { return base(new io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat()); }
  public io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat base(io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat fields(int j) { return fields(new io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat(), j); }
  public io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat fields(io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int fieldsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat.Vector fieldsVector() { return fieldsVector(new io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat.Vector()); }
  public io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat.Vector fieldsVector(io.pixelsdb.pixels.core.utils.flat.ColumnVectorBaseFlat.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createStructColumnVectorFlat(FlatBufferBuilder builder,
      int baseOffset,
      int fieldsOffset) {
    builder.startTable(2);
    StructColumnVectorFlat.addFields(builder, fieldsOffset);
    StructColumnVectorFlat.addBase(builder, baseOffset);
    return StructColumnVectorFlat.endStructColumnVectorFlat(builder);
  }

  public static void startStructColumnVectorFlat(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addBase(FlatBufferBuilder builder, int baseOffset) { builder.addOffset(0, baseOffset, 0); }
  public static void addFields(FlatBufferBuilder builder, int fieldsOffset) { builder.addOffset(1, fieldsOffset, 0); }
  public static int createFieldsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFieldsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endStructColumnVectorFlat(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StructColumnVectorFlat get(int j) { return get(new StructColumnVectorFlat(), j); }
    public StructColumnVectorFlat get(StructColumnVectorFlat obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

