/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_ruc_iir_pixels_cache_TestJni */

#ifndef _Included_cn_edu_ruc_iir_pixels_cache_TestJni
#define _Included_cn_edu_ruc_iir_pixels_cache_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_ruc_iir_pixels_cache_TestJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_edu_ruc_iir_pixels_cache_TestJni_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     cn_edu_ruc_iir_pixels_cache_TestJni
 * Method:    add
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_edu_ruc_iir_pixels_cache_TestJni_add
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_edu_ruc_iir_pixels_cache_TestJni
 * Method:    echo
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_edu_ruc_iir_pixels_cache_TestJni_echo
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
