/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pixelsdb_pixels_cache_TestJni */

#ifndef _Included_io_pixelsdb_pixels_cache_TestJni
#define _Included_io_pixelsdb_pixels_cache_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pixelsdb_pixels_cache_TestJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pixelsdb_pixels_cache_TestJni_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     io_pixelsdb_pixels_cache_TestJni
 * Method:    add
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_pixelsdb_pixels_cache_TestJni_add
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_pixelsdb_pixels_cache_TestJni
 * Method:    echo
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pixelsdb_pixels_cache_TestJni_echo
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
