-- Create the Derby metadata tables for Pixels.

-- -----------------------------------------------------
-- Table DBS
-- -----------------------------------------------------
CREATE TABLE DBS (
    DB_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    DB_NAME VARCHAR(128) NOT NULL,
    DB_DESC VARCHAR(4000),
    PRIMARY KEY (DB_ID)
);
CREATE UNIQUE INDEX DB_NAME_UNIQUE ON DBS (DB_NAME);

-- -----------------------------------------------------
-- Table TBLS
-- -----------------------------------------------------
CREATE TABLE TBLS (
    TBL_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    TBL_NAME VARCHAR(128) NOT NULL,
    TBL_TYPE VARCHAR(128),
    TBL_STORAGE_SCHEME VARCHAR(32) NOT NULL DEFAULT 'file',
    TBL_ROW_COUNT BIGINT NOT NULL DEFAULT 0,
    DBS_DB_ID BIGINT NOT NULL,
    PRIMARY KEY (TBL_ID),
    CONSTRAINT fk_TBLS_DBS
        FOREIGN KEY (DBS_DB_ID)
            REFERENCES DBS (DB_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_TBLS_DBS_idx ON TBLS (DBS_DB_ID);
CREATE UNIQUE INDEX TBL_NAME_DB_ID_UNIQUE ON TBLS (TBL_NAME, DBS_DB_ID);

-- -----------------------------------------------------
-- Table COLS
-- -----------------------------------------------------
CREATE TABLE COLS (
    COL_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    COL_NAME VARCHAR(128) NOT NULL,
    COL_TYPE VARCHAR(128) NOT NULL,
    COL_CHUNK_SIZE DOUBLE NOT NULL DEFAULT 0,
    COL_SIZE DOUBLE NOT NULL DEFAULT 0,
    COL_NULL_FRACTION DOUBLE NOT NULL DEFAULT 0,
    COL_CARDINALITY BIGINT NOT NULL DEFAULT 0,
    COL_RECORD_STATS BLOB,
    TBLS_TBL_ID BIGINT NOT NULL,
    PRIMARY KEY (COL_ID),
    CONSTRAINT fk_COLS_TBLS
        FOREIGN KEY (TBLS_TBL_ID)
            REFERENCES TBLS (TBL_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_COLS_TBLS_idx ON COLS (TBLS_TBL_ID);
CREATE UNIQUE INDEX COL_NAME_TBL_ID_UNIQUE ON COLS (COL_NAME, TBLS_TBL_ID);

-- -----------------------------------------------------
-- Table SCHEMA_VERSIONS
-- -----------------------------------------------------
CREATE TABLE SCHEMA_VERSIONS (
    SV_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    SV_COLUMNS CLOB NOT NULL,
    SV_TRANS_TS BIGINT NOT NULL,
    TBLS_TBL_ID BIGINT NOT NULL,
    PRIMARY KEY (SV_ID),
    CONSTRAINT fk_SCHEMA_VERSIONS_TBLS
        FOREIGN KEY (TBLS_TBL_ID)
            REFERENCES TBLS (TBL_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_SCHEMA_VERSIONS_TBLS_idx ON SCHEMA_VERSIONS (TBLS_TBL_ID);

-- -----------------------------------------------------
-- Table LAYOUTS
-- -----------------------------------------------------
CREATE TABLE LAYOUTS (
    LAYOUT_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    LAYOUT_VERSION BIGINT NOT NULL,
    LAYOUT_CREATE_AT BIGINT NOT NULL,
    LAYOUT_PERMISSION SMALLINT NOT NULL,
    LAYOUT_ORDERED CLOB NOT NULL,
    LAYOUT_COMPACT CLOB NOT NULL,
    LAYOUT_SPLITS CLOB NOT NULL,
    LAYOUT_PROJECTIONS CLOB NOT NULL,
    TBLS_TBL_ID BIGINT NOT NULL,
    SCHEMA_VERSIONS_SV_ID BIGINT NOT NULL,
    PRIMARY KEY (LAYOUT_ID),
    CONSTRAINT fk_LAYOUTS_TBLS
        FOREIGN KEY (TBLS_TBL_ID)
            REFERENCES TBLS (TBL_ID)
            ON DELETE CASCADE,
    CONSTRAINT fk_LAYOUTS_SCHEMA_VERSIONS
        FOREIGN KEY (SCHEMA_VERSIONS_SV_ID)
            REFERENCES SCHEMA_VERSIONS (SV_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_LAYOUTS_TBLS_idx ON LAYOUTS (TBLS_TBL_ID);
CREATE INDEX fk_LAYOUTS_SCHEMA_VERSIONS_idx ON LAYOUTS (SCHEMA_VERSIONS_SV_ID);

-- -----------------------------------------------------
-- Table VIEWS
-- -----------------------------------------------------
CREATE TABLE VIEWS (
    VIEW_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    VIEW_NAME VARCHAR(128) NOT NULL,
    VIEW_TYPE VARCHAR(128),
    VIEW_DATA CLOB NOT NULL,
    DBS_DB_ID BIGINT NOT NULL,
    PRIMARY KEY (VIEW_ID),
    CONSTRAINT fk_VIEWS_DBS
        FOREIGN KEY (DBS_DB_ID)
            REFERENCES DBS (DB_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_VIEWS_DBS_idx ON VIEWS (DBS_DB_ID);

-- -----------------------------------------------------
-- Table RANGE_INDICES
-- -----------------------------------------------------
CREATE TABLE RANGE_INDICES (
    RI_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    RI_KEY_COLUMNS CLOB NOT NULL,
    TBLS_TBL_ID BIGINT NOT NULL,
    SCHEMA_VERSIONS_SV_ID BIGINT NOT NULL,
    PRIMARY KEY (RI_ID),
    CONSTRAINT fk_RANGE_INDICES_TBLS
        FOREIGN KEY (TBLS_TBL_ID)
            REFERENCES TBLS (TBL_ID)
            ON DELETE CASCADE,
    CONSTRAINT fk_RANGE_INDICES_SCHEMA_VERSIONS
        FOREIGN KEY (SCHEMA_VERSIONS_SV_ID)
            REFERENCES SCHEMA_VERSIONS (SV_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_RANGE_INDICES_TBLS_idx ON RANGE_INDICES (TBLS_TBL_ID);
CREATE INDEX fk_RANGE_INDICES_SCHEMA_VERSIONS_idx ON RANGE_INDICES (SCHEMA_VERSIONS_SV_ID);
CREATE UNIQUE INDEX TBL_ID_SV_ID_UNIQUE ON RANGE_INDICES (TBLS_TBL_ID, SCHEMA_VERSIONS_SV_ID);

-- -----------------------------------------------------
-- Table RANGES
-- -----------------------------------------------------
CREATE TABLE RANGES (
    RANGE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    RANGE_MIN BLOB NOT NULL,
    RANGE_MAX BLOB NOT NULL,
    RANGE_PARENT_ID BIGINT,
    RANGE_INDICES_RI_ID BIGINT NOT NULL,
    PRIMARY KEY (RANGE_ID),
    CONSTRAINT fk_RANGES_RANGE_INDICES
        FOREIGN KEY (RANGE_INDICES_RI_ID)
            REFERENCES RANGE_INDICES (RI_ID)
            ON DELETE CASCADE,
    CONSTRAINT fk_RANGES_RANGES
        FOREIGN KEY (RANGE_PARENT_ID)
            REFERENCES RANGES (RANGE_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_RANGES_RANGE_INDICES_idx ON RANGES (RANGE_INDICES_RI_ID);
CREATE INDEX fk_RANGES_RANGES_idx ON RANGES (RANGE_PARENT_ID);

-- -----------------------------------------------------
-- Table PATHS
-- -----------------------------------------------------
CREATE TABLE PATHS (
    PATH_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    PATH_URI VARCHAR(512) NOT NULL,
    PATH_TYPE SMALLINT NOT NULL,
    LAYOUTS_LAYOUT_ID BIGINT NOT NULL,
    RANGES_RANGE_ID BIGINT,
    PRIMARY KEY (PATH_ID),
    CONSTRAINT fk_PATHS_RANGES
        FOREIGN KEY (RANGES_RANGE_ID)
            REFERENCES RANGES (RANGE_ID)
            ON DELETE CASCADE,
    CONSTRAINT fk_PATHS_LAYOUTS
        FOREIGN KEY (LAYOUTS_LAYOUT_ID)
            REFERENCES LAYOUTS (LAYOUT_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_PATHS_RANGES_idx ON PATHS (RANGES_RANGE_ID);
CREATE INDEX fk_PATHS_LAYOUTS_idx ON PATHS (LAYOUTS_LAYOUT_ID);
CREATE UNIQUE INDEX PATH_URI_UNIQUE ON PATHS (PATH_URI);

-- -----------------------------------------------------
-- Table USERS
-- -----------------------------------------------------
CREATE TABLE USERS (
    USER_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    USER_NAME VARCHAR(128) NOT NULL,
    USER_PASSWORD VARCHAR(128) NOT NULL,
    USER_EMAIL VARCHAR(128) NOT NULL,
    PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX USER_NAME_UNIQUE ON USERS (USER_NAME);

-- -----------------------------------------------------
-- Table USER_HAS_DB
-- -----------------------------------------------------
CREATE TABLE USER_HAS_DB (
    USERS_USER_ID BIGINT NOT NULL,
    DBS_DB_ID BIGINT NOT NULL,
    USER_DB_PERMITION SMALLINT NOT NULL,
    PRIMARY KEY (USERS_USER_ID, DBS_DB_ID),
    CONSTRAINT fk_USERS_has_DBS_USERS
        FOREIGN KEY (USERS_USER_ID)
            REFERENCES USERS (USER_ID)
            ON DELETE CASCADE,
    CONSTRAINT fk_USERS_has_DBS_DBS
        FOREIGN KEY (DBS_DB_ID)
            REFERENCES DBS (DB_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_USERS_has_DBS_DBS_idx ON USER_HAS_DB (DBS_DB_ID);
CREATE INDEX fk_USERS_has_DBS_USERS_idx ON USER_HAS_DB (USERS_USER_ID);

-- -----------------------------------------------------
-- Table PEERS
-- -----------------------------------------------------
CREATE TABLE PEERS (
    PEER_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    PEER_NAME VARCHAR(128) NOT NULL,
    PEER_LOCATION VARCHAR(1024) NOT NULL,
    PEER_HOST VARCHAR(128) NOT NULL,
    PEER_PORT INT NOT NULL,
    PEER_STORAGE_SCHEME VARCHAR(32) NOT NULL,
    PRIMARY KEY (PEER_ID)
);
CREATE UNIQUE INDEX PEER_NAME_UNIQUE ON PEERS (PEER_NAME);

-- -----------------------------------------------------
-- Table PEER_PATHS
-- -----------------------------------------------------
CREATE TABLE PEER_PATHS (
    PEER_PATH_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    PEER_PATH_URI VARCHAR(32) NOT NULL,
    PEER_PATH_COLUMNS CLOB NOT NULL,
    PATHS_PATH_ID BIGINT NOT NULL,
    PEERS_PEER_ID BIGINT NOT NULL,
    PRIMARY KEY (PEER_PATH_ID),
    CONSTRAINT fk_PEER_PATHS_PATHS
        FOREIGN KEY (PATHS_PATH_ID)
            REFERENCES PATHS (PATH_ID)
            ON DELETE CASCADE,
    CONSTRAINT fk_PEER_PATHS_PEERS
        FOREIGN KEY (PEERS_PEER_ID)
            REFERENCES PEERS (PEER_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_PEER_PATHS_PATHS_idx ON PEER_PATHS (PATHS_PATH_ID);
CREATE INDEX fk_PEER_PATHS_PEERS_idx ON PEER_PATHS (PEERS_PEER_ID);

-- -----------------------------------------------------
-- Table FILES
-- -----------------------------------------------------
CREATE TABLE FILES (
    FILE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    FILE_NAME VARCHAR(128) NOT NULL,
    FILE_TYPE SMALLINT NOT NULL,
    FILE_NUM_RG INT NOT NULL,
    FILE_MIN_ROW_ID BIGINT NOT NULL,
    FILE_MAX_ROW_ID BIGINT NOT NULL,
    FILE_CLEANUP_AT BIGINT,
    PATHS_PATH_ID BIGINT NOT NULL,
    PRIMARY KEY (FILE_ID),
    CONSTRAINT fk_FILES_PATHS
        FOREIGN KEY (PATHS_PATH_ID)
            REFERENCES PATHS (PATH_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_FILES_PATHS_idx ON FILES (PATHS_PATH_ID);
CREATE UNIQUE INDEX PATH_ID_FILE_NAME_UNIQUE ON FILES (PATHS_PATH_ID, FILE_NAME);
CREATE INDEX FILE_ROW_ID_INDEX ON FILES (FILE_MIN_ROW_ID, FILE_MAX_ROW_ID);

-- -----------------------------------------------------
-- Table SINGLE_POINT_INDICES
-- -----------------------------------------------------
CREATE TABLE SINGLE_POINT_INDICES (
    SPI_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    SPI_KEY_COLUMNS CLOB NOT NULL,
    SPI_PRIMARY SMALLINT NOT NULL,
    SPI_UNIQUE SMALLINT NOT NULL,
    SPI_INDEX_SCHEME VARCHAR(32) NOT NULL,
    TBLS_TBL_ID BIGINT NOT NULL,
    SCHEMA_VERSIONS_SV_ID BIGINT NOT NULL,
    PRIMARY KEY (SPI_ID),
    CONSTRAINT fk_SINGLE_POINT_INDICES_TBLS
        FOREIGN KEY (TBLS_TBL_ID)
            REFERENCES TBLS (TBL_ID)
            ON DELETE CASCADE,
    CONSTRAINT fk_SINGLE_POINT_INDICES_SCHEMA_VERSIONS
        FOREIGN KEY (SCHEMA_VERSIONS_SV_ID)
            REFERENCES SCHEMA_VERSIONS (SV_ID)
            ON DELETE CASCADE
);
CREATE INDEX fk_SINGLE_POINT_INDICES_TBLS_idx ON SINGLE_POINT_INDICES (TBLS_TBL_ID);
CREATE INDEX fk_SINGLE_POINT_INDICES_SCHEMA_VERSIONS_idx ON SINGLE_POINT_INDICES (SCHEMA_VERSIONS_SV_ID);
