#!/usr/bin/env bash
set -euo pipefail

# Optional convenience step (asks before doing anything - see below):
# writes start_trino_cluster/stop_trino_cluster/restart_trino_cluster/
# change_trino_version/trino_cli shell functions, driven by the cluster
# topology written by prepare_trino_cluster.sh. The coordinator is operated
# locally; every worker is operated over the passwordless SSH that
# prepare_trino_cluster.sh (via agents/scripts/setup_cluster.sh) already set
# up between cluster nodes.
#
# Unlike install_shell_helpers.sh's pixels start/stop/restart (purely local,
# no other host involved), this writes a specific list of remote hostnames
# into the user's shell profile and assumes passwordless SSH is already in
# place - so, like the etcd systemd unit, we ask before installing it
# instead of doing it silently.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/shell_env.sh
source "$SCRIPT_DIR/lib/shell_env.sh"

AGENT_DIR="${AGENT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
TRINO_DEPLOYMENT_FILE="${TRINO_DEPLOYMENT_FILE:-$AGENT_DIR/trino-deployment.env}"
if [[ -f "$TRINO_DEPLOYMENT_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$TRINO_DEPLOYMENT_FILE"
  set +a
fi

SSH_USER="${SSH_USER:-root}"
TRINO_HTTP_PORT="${TRINO_HTTP_PORT:-8080}"
TRINO_FUNCTIONS_FILE="${TRINO_FUNCTIONS_FILE:-$HOME/.trino-shell-helpers.sh}"
ASSUME_YES="${ASSUME_YES:-false}"
INSTALL_TRINO_SHELL_HELPERS="${INSTALL_TRINO_SHELL_HELPERS:-}"

log() {
  printf '[%s] %s\n' "$(date '+%H:%M:%S')" "$*"
}

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

# Same "ask, don't assume" pattern as install_etcd.sh's confirm_systemd_service.
confirm_install() {
  local reply

  case "$INSTALL_TRINO_SHELL_HELPERS" in
    true) return 0 ;;
    false) return 1 ;;
  esac

  [[ "$ASSUME_YES" == "true" ]] && return 0

  if [[ ! -t 0 ]]; then
    log "not running interactively and INSTALL_TRINO_SHELL_HELPERS/ASSUME_YES not set; skipping the trino shell helpers. Set INSTALL_TRINO_SHELL_HELPERS=true once the user has agreed."
    return 1
  fi

  read -r -p "Install start_trino_cluster/stop_trino_cluster/restart_trino_cluster/change_trino_version/trino_cli shell functions for this cluster (writes $TRINO_FUNCTIONS_FILE)? [y/N]: " reply
  [[ "$reply" =~ ^[Yy]$ ]]
}

remote_spec() {
  local target="$1"
  if [[ -n "$SSH_USER" && "$target" != *@* ]]; then
    printf '%s@%s' "$SSH_USER" "$target"
  else
    printf '%s' "$target"
  fi
}

# Coordinator first (operated locally by the generated functions), then
# every worker (operated over SSH).
build_node_list() {
  local node

  [[ -n "${TRINO_COORDINATOR_SSH_TARGET:-}" ]] ||
    fail "TRINO_COORDINATOR_SSH_TARGET is unknown; run prepare_trino_cluster.sh first, or set TRINO_COORDINATOR_SSH_TARGET/TRINO_WORKER_SSH_TARGETS explicitly"

  TRINO_NODE_LIST=("$(remote_spec "$TRINO_COORDINATOR_SSH_TARGET")")
  for node in ${TRINO_WORKER_SSH_TARGETS:-}; do
    TRINO_NODE_LIST+=("$(remote_spec "$node")")
  done
}

write_functions_file() {
  local nodes_literal node

  nodes_literal=""
  for node in "${TRINO_NODE_LIST[@]}"; do
    nodes_literal+="  \"$node\"
"
  done

  log "writing trino cluster shell functions to $TRINO_FUNCTIONS_FILE (${#TRINO_NODE_LIST[@]} node(s), coordinator first)"

  cat > "$TRINO_FUNCTIONS_FILE" <<EOF
# Generated by pixels-install/scripts/install_trino_shell_helpers.sh
# TRINO_NODES[0] is the coordinator and is always operated locally; the rest
# are workers, operated over the passwordless SSH set up by
# prepare_trino_cluster.sh. Re-run install_trino_shell_helpers.sh to
# regenerate this file after the cluster topology changes.

TRINO_NODES=(
$nodes_literal)

_trino_home() {
  printf '%s\n' "\${TRINO_HOME_LINK:-\$HOME/opt/trino-server}"
}

start_trino_cluster() {
  local node first=true

  for node in "\${TRINO_NODES[@]}"; do
    if [[ "\$first" == "true" ]]; then
      echo "starting trino on \$node (coordinator, local)"
      "\$(_trino_home)/bin/launcher" start || { echo "failed to start coordinator \$node" >&2; return 1; }
      first=false
    else
      echo "starting trino on \$node (worker, remote)"
      ssh -n "\$node" '~/opt/trino-server/bin/launcher start' || { echo "failed to start worker \$node" >&2; return 1; }
    fi
  done

  echo "trino cluster started"
}

stop_trino_cluster() {
  local node first=true

  for node in "\${TRINO_NODES[@]}"; do
    if [[ "\$first" == "true" ]]; then
      echo "stopping trino on \$node (coordinator, local)"
      "\$(_trino_home)/bin/launcher" stop || { echo "failed to stop coordinator \$node" >&2; return 1; }
      first=false
    else
      echo "stopping trino on \$node (worker, remote)"
      ssh -n "\$node" '~/opt/trino-server/bin/launcher stop' || { echo "failed to stop worker \$node" >&2; return 1; }
    fi
  done

  echo "trino cluster stopped"
}

restart_trino_cluster() {
  local node first=true

  for node in "\${TRINO_NODES[@]}"; do
    if [[ "\$first" == "true" ]]; then
      echo "restarting trino on \$node (coordinator, local)"
      "\$(_trino_home)/bin/launcher" restart || { echo "failed to restart coordinator \$node" >&2; return 1; }
      first=false
    else
      echo "restarting trino on \$node (worker, remote)"
      ssh -n "\$node" '~/opt/trino-server/bin/launcher restart' || { echo "failed to restart worker \$node" >&2; return 1; }
    fi
  done

  echo "trino cluster restarted"
}

# Re-links ~/opt/trino-server -> ~/opt/trino-server-<version> on every node
# (including the coordinator, over SSH to itself), so a freshly installed
# version takes effect on next start/restart.
change_trino_version() {
  local version="\$1" node target_dir link_name="trino-server"

  if [[ -z "\$version" ]]; then
    echo "usage: change_trino_version <version>"
    return 1
  fi
  target_dir="trino-server-\$version"

  echo "switching every node to Trino \$version..."
  for node in "\${TRINO_NODES[@]}"; do
    echo "--- \$node ---"
    ssh -n "\$node" "cd ~/opt && if [ -d '\$target_dir' ]; then ln -sfn '\$target_dir' '\$link_name' && echo 'linked \$link_name -> \$target_dir'; else echo 'ERROR: ~/opt/'\$target_dir' does not exist'; fi"
  done
}

trino_cli() {
  local catalog="\${1:-pixels}"
  "\$(_trino_home)/bin/trino" --server "localhost:\${TRINO_HTTP_PORT:-$TRINO_HTTP_PORT}" --catalog "\$catalog"
}
EOF

  chmod 644 "$TRINO_FUNCTIONS_FILE"
}

persist_source_line() {
  local profile_file line

  profile_file="$(detect_profile_file)"
  line="[ -f \"$TRINO_FUNCTIONS_FILE\" ] && source \"$TRINO_FUNCTIONS_FILE\""

  log "persisting source line for $TRINO_FUNCTIONS_FILE in $profile_file"
  persist_line "$profile_file" "$line"
}

main() {
  if ! confirm_install; then
    log "skipping trino shell helpers (not confirmed)"
    return 0
  fi

  build_node_list
  write_functions_file
  bash -n "$TRINO_FUNCTIONS_FILE" || fail "generated functions file has a syntax error: $TRINO_FUNCTIONS_FILE"
  persist_source_line

  log "trino shell helpers installed: start_trino_cluster, stop_trino_cluster, restart_trino_cluster, change_trino_version, trino_cli"
  log "open a new terminal (or run: source $(detect_profile_file)) to use them"
}

main "$@"
