// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: retina_writer.proto

package io.pixelsdb.pixels.retina;

public final class RetinaWriterProto {
  private RetinaWriterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FlushRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:retina_writer.proto.FlushRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string schemaName = 1;</code>
     */
    java.lang.String getSchemaName();
    /**
     * <code>string schemaName = 1;</code>
     */
    com.google.protobuf.ByteString
        getSchemaNameBytes();

    /**
     * <code>string tableName = 2;</code>
     */
    java.lang.String getTableName();
    /**
     * <code>string tableName = 2;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    /**
     * <code>sint32 rgid = 3;</code>
     */
    int getRgid();

    /**
     * <code>string filePath = 4;</code>
     */
    java.lang.String getFilePath();
    /**
     * <code>string filePath = 4;</code>
     */
    com.google.protobuf.ByteString
        getFilePathBytes();

    /**
     * <code>uint64 pos = 5;</code>
     */
    long getPos();
  }
  /**
   * Protobuf type {@code retina_writer.proto.FlushRequest}
   */
  public  static final class FlushRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:retina_writer.proto.FlushRequest)
      FlushRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlushRequest.newBuilder() to construct.
    private FlushRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlushRequest() {
      schemaName_ = "";
      tableName_ = "";
      rgid_ = 0;
      filePath_ = "";
      pos_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlushRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              schemaName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            case 24: {

              rgid_ = input.readSInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              filePath_ = s;
              break;
            }
            case 40: {

              pos_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest.class, io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest.Builder.class);
    }

    public static final int SCHEMANAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object schemaName_;
    /**
     * <code>string schemaName = 1;</code>
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      }
    }
    /**
     * <code>string schemaName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object tableName_;
    /**
     * <code>string tableName = 2;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <code>string tableName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RGID_FIELD_NUMBER = 3;
    private int rgid_;
    /**
     * <code>sint32 rgid = 3;</code>
     */
    public int getRgid() {
      return rgid_;
    }

    public static final int FILEPATH_FIELD_NUMBER = 4;
    private volatile java.lang.Object filePath_;
    /**
     * <code>string filePath = 4;</code>
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }
    /**
     * <code>string filePath = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POS_FIELD_NUMBER = 5;
    private long pos_;
    /**
     * <code>uint64 pos = 5;</code>
     */
    public long getPos() {
      return pos_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSchemaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schemaName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tableName_);
      }
      if (rgid_ != 0) {
        output.writeSInt32(3, rgid_);
      }
      if (!getFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, filePath_);
      }
      if (pos_ != 0L) {
        output.writeUInt64(5, pos_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSchemaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schemaName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tableName_);
      }
      if (rgid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, rgid_);
      }
      if (!getFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, filePath_);
      }
      if (pos_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, pos_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest)) {
        return super.equals(obj);
      }
      io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest other = (io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest) obj;

      boolean result = true;
      result = result && getSchemaName()
          .equals(other.getSchemaName());
      result = result && getTableName()
          .equals(other.getTableName());
      result = result && (getRgid()
          == other.getRgid());
      result = result && getFilePath()
          .equals(other.getFilePath());
      result = result && (getPos()
          == other.getPos());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMANAME_FIELD_NUMBER;
      hash = (53 * hash) + getSchemaName().hashCode();
      hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      hash = (37 * hash) + RGID_FIELD_NUMBER;
      hash = (53 * hash) + getRgid();
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (37 * hash) + POS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPos());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code retina_writer.proto.FlushRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:retina_writer.proto.FlushRequest)
        io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest.class, io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest.Builder.class);
      }

      // Construct using io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schemaName_ = "";

        tableName_ = "";

        rgid_ = 0;

        filePath_ = "";

        pos_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushRequest_descriptor;
      }

      @java.lang.Override
      public io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest getDefaultInstanceForType() {
        return io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest build() {
        io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest buildPartial() {
        io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest result = new io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest(this);
        result.schemaName_ = schemaName_;
        result.tableName_ = tableName_;
        result.rgid_ = rgid_;
        result.filePath_ = filePath_;
        result.pos_ = pos_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest) {
          return mergeFrom((io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest other) {
        if (other == io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest.getDefaultInstance()) return this;
        if (!other.getSchemaName().isEmpty()) {
          schemaName_ = other.schemaName_;
          onChanged();
        }
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        if (other.getRgid() != 0) {
          setRgid(other.getRgid());
        }
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          onChanged();
        }
        if (other.getPos() != 0L) {
          setPos(other.getPos());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object schemaName_ = "";
      /**
       * <code>string schemaName = 1;</code>
       */
      public java.lang.String getSchemaName() {
        java.lang.Object ref = schemaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schemaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string schemaName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSchemaNameBytes() {
        java.lang.Object ref = schemaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schemaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string schemaName = 1;</code>
       */
      public Builder setSchemaName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schemaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string schemaName = 1;</code>
       */
      public Builder clearSchemaName() {
        
        schemaName_ = getDefaultInstance().getSchemaName();
        onChanged();
        return this;
      }
      /**
       * <code>string schemaName = 1;</code>
       */
      public Builder setSchemaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schemaName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tableName_ = "";
      /**
       * <code>string tableName = 2;</code>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tableName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tableName = 2;</code>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tableName = 2;</code>
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <code>string tableName = 2;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }

      private int rgid_ ;
      /**
       * <code>sint32 rgid = 3;</code>
       */
      public int getRgid() {
        return rgid_;
      }
      /**
       * <code>sint32 rgid = 3;</code>
       */
      public Builder setRgid(int value) {
        
        rgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 rgid = 3;</code>
       */
      public Builder clearRgid() {
        
        rgid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object filePath_ = "";
      /**
       * <code>string filePath = 4;</code>
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filePath = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filePath = 4;</code>
       */
      public Builder setFilePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filePath = 4;</code>
       */
      public Builder clearFilePath() {
        
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      /**
       * <code>string filePath = 4;</code>
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filePath_ = value;
        onChanged();
        return this;
      }

      private long pos_ ;
      /**
       * <code>uint64 pos = 5;</code>
       */
      public long getPos() {
        return pos_;
      }
      /**
       * <code>uint64 pos = 5;</code>
       */
      public Builder setPos(long value) {
        
        pos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 pos = 5;</code>
       */
      public Builder clearPos() {
        
        pos_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:retina_writer.proto.FlushRequest)
    }

    // @@protoc_insertion_point(class_scope:retina_writer.proto.FlushRequest)
    private static final io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest();
    }

    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlushRequest>
        PARSER = new com.google.protobuf.AbstractParser<FlushRequest>() {
      @java.lang.Override
      public FlushRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlushRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlushRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlushRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.pixelsdb.pixels.retina.RetinaWriterProto.FlushRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FlushResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:retina_writer.proto.FlushResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 errorCode = 1;</code>
     */
    int getErrorCode();

    /**
     * <code>uint64 pos = 2;</code>
     */
    long getPos();
  }
  /**
   * Protobuf type {@code retina_writer.proto.FlushResponse}
   */
  public  static final class FlushResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:retina_writer.proto.FlushResponse)
      FlushResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlushResponse.newBuilder() to construct.
    private FlushResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlushResponse() {
      errorCode_ = 0;
      pos_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlushResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
            case 16: {

              pos_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse.class, io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int POS_FIELD_NUMBER = 2;
    private long pos_;
    /**
     * <code>uint64 pos = 2;</code>
     */
    public long getPos() {
      return pos_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
      if (pos_ != 0L) {
        output.writeUInt64(2, pos_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      if (pos_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, pos_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse)) {
        return super.equals(obj);
      }
      io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse other = (io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse) obj;

      boolean result = true;
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && (getPos()
          == other.getPos());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (37 * hash) + POS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPos());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code retina_writer.proto.FlushResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:retina_writer.proto.FlushResponse)
        io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse.class, io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse.Builder.class);
      }

      // Construct using io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        pos_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.pixelsdb.pixels.retina.RetinaWriterProto.internal_static_retina_writer_proto_FlushResponse_descriptor;
      }

      @java.lang.Override
      public io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse getDefaultInstanceForType() {
        return io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse build() {
        io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse buildPartial() {
        io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse result = new io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse(this);
        result.errorCode_ = errorCode_;
        result.pos_ = pos_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse) {
          return mergeFrom((io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse other) {
        if (other == io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (other.getPos() != 0L) {
          setPos(other.getPos());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private long pos_ ;
      /**
       * <code>uint64 pos = 2;</code>
       */
      public long getPos() {
        return pos_;
      }
      /**
       * <code>uint64 pos = 2;</code>
       */
      public Builder setPos(long value) {
        
        pos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 pos = 2;</code>
       */
      public Builder clearPos() {
        
        pos_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:retina_writer.proto.FlushResponse)
    }

    // @@protoc_insertion_point(class_scope:retina_writer.proto.FlushResponse)
    private static final io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse();
    }

    public static io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlushResponse>
        PARSER = new com.google.protobuf.AbstractParser<FlushResponse>() {
      @java.lang.Override
      public FlushResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlushResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlushResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlushResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.pixelsdb.pixels.retina.RetinaWriterProto.FlushResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_retina_writer_proto_FlushRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_retina_writer_proto_FlushRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_retina_writer_proto_FlushResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_retina_writer_proto_FlushResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023retina_writer.proto\022\023retina_writer.pro" +
      "to\"b\n\014FlushRequest\022\022\n\nschemaName\030\001 \001(\t\022\021" +
      "\n\ttableName\030\002 \001(\t\022\014\n\004rgid\030\003 \001(\021\022\020\n\010fileP" +
      "ath\030\004 \001(\t\022\013\n\003pos\030\005 \001(\004\"/\n\rFlushResponse\022" +
      "\021\n\terrorCode\030\001 \001(\005\022\013\n\003pos\030\002 \001(\0042e\n\023Retin" +
      "aWriterService\022N\n\005Flush\022!.retina_writer." +
      "proto.FlushRequest\032\".retina_writer.proto" +
      ".FlushResponseB0\n\031io.pixelsdb.pixels.ret" +
      "inaB\021RetinaWriterProtoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_retina_writer_proto_FlushRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_retina_writer_proto_FlushRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_retina_writer_proto_FlushRequest_descriptor,
        new java.lang.String[] { "SchemaName", "TableName", "Rgid", "FilePath", "Pos", });
    internal_static_retina_writer_proto_FlushResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_retina_writer_proto_FlushResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_retina_writer_proto_FlushResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "Pos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
